# Generated by Django 6.0.4 on 2026-04-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='service',
        ),
    ]
