# Generated by Django 6.0.4 on 2026-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('antecedents', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
            },
        ),
    ]
