# Generated by Django 6.0.4 on 2026-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(max_length=50)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('date_prise_poste', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
    ]
