# Generated by Django 6.0.4 on 2026-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
    ]
